### ISSUE TITLE
Support for fine tuning, aka training the model of incoming data from the cluster in which it is deployed

### ISSUE THREAD

**Issue by Jaffenheimer** [aau-p9s/Autoscaler#10]
Vi når til et punkt hvor der skal scales op, vi scalerer op.
Der går lidt tid, vi skal skalere igen, inden vi skalerer sammenligner vi forecasten med actual cpu percentage, hvis de er nogenlunde ens skaleres der igen, hvis der er stor foreskel, gentrænes modellen på det nye data der er opsamlet fra prometheus og der laves en ny forecast, inden der tages stilling til om der skal scales igen.

**Comment by Mast3rwaf1z** [comment]
Underlying issue is that a forecast does not have the context of the underlying amount of replicas
